spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
    group:
      dev:
        - local-dev
        - debug
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  liquibase:
    change-log: classpath:/liquibase/db.changelog-master.xml

server:
  error:
    include-message: always
    include-binding-errors: always
  port: ${SERVER_PORT}
  servlet:
    context-path: /admin

springdoc:
  show-actuator: true

management:
  endpoint:
    health:
      show-details: when_authorized

airgear:
  admin:
    security:
      jwt:
        secret: signingkey
        key: roles
      admins:
        first:
          email: admin@gmail.com
          password: qwertyui

entity:
  constraint: 30